#!/usr/bin/env bash
# install nginx on web server, Nginx should be listening on port 80
# print :hello World!"

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
